### ISSUE TITLE
v0.5.0 broken due to error in entrypoint.sh

### ISSUE THREAD

**Issue by hadim** [aevea/action-kaniko#10]
The error is:

```
INFO[0078] SHELL ["/bin/bash", "--login", "-c"]         
INFO[0078] No files changed in this command, skipping snapshotting. 
INFO[0078] ENTRYPOINT ["/entrypoint.sh"]                
INFO[0078] No files changed in this command, skipping snapshotting. 
INFO[0114] Skipping push to container registry due to --no-push flag 
/entrypoint.sh: line 93: syntax error: unexpected end of file (expecting "fi")
```
The registry is gcr.io and I use `elgohr/gcloud-login-action@0.2` to get username and password.

**Comment by aexvir** [comment]
This repository is using the latest version of the action and it looks ok. I’m not using gcr.io do not sure if it’s something specific to that registry 

Could you provide some more info so I can reproduce the issue?

Cc @somdoron as you contributed to the last version

**Comment by aexvir** [comment]
I'm going to close this
Feel free to reopen if you can provide a reproducible use case 🙂
