### ISSUE TITLE
make sure v0.6.1 is displayed as latest version in the github marketplace

### ISSUE THREAD

**Issue by fsperling** [aevea/action-kaniko#21]
Hi,

Thank you for providing this action. 

Could you please make sure v0.6.1 is displayed as latest version in the github marketplace. Currently the marketplace refers to v0.6.0 as latest which has the bug that the image can't be build.

Cheers,
Felix

![image](https://user-images.githubusercontent.com/1224515/115017986-97ec9480-9eb7-11eb-965b-0861a3a910df.png)

**Comment by aexvir** [comment]
hmm... sorry for not seeing this on time 😞 not sure what happened, but now it correctly displays the latest version available
![Screenshot 2022-01-24 at 10 50 11](https://user-images.githubusercontent.com/8055505/150760041-7e43ee80-c097-4095-bfbf-f0580118618e.png)
