### ISSUE TITLE
Feature Request: --reproducible flag and skip Push on Unchanged Digest

### ISSUE THREAD

**Issue by somdoron** [aevea/action-kaniko#5]
I have a monorepo with multiple docker images and I would like to publish an image only if the digest of the image is not present in the registry, regardless of the tag. I'm using fluxcd and right now because a tag is pushed on every push to master, all the pods are being restarted.

Kaniko supports the reproducible flag, this action now supports it through the `extra_args`, I suggest to make it a first-class variable. 

Anyway, I suggest the option skipUnchangedDigest to the build-push-action and when set to true the action will skip the push if the digest already present.

Bazel build supports this with skipUnchangedDigest flag to the container_push rule, code is here:
https://github.com/bazelbuild/rules_docker/blob/06c5419265e84baf168ba4d3982f45fe1fe312b4/container/go/cmd/pusher/pusher.go#L132
https://github.com/bazelbuild/rules_docker/blob/06c5419265e84baf168ba4d3982f45fe1fe312b4/container/go/cmd/pusher/pusher.go#L163

I will be happy to try and contribute those, however, I'm not sure how to implement the skipUnchangedDigest. Pointers are welcome.

**Comment by hadim** [comment]
I am also interested in that feature.

xref with https://github.com/docker/build-push-action/issues/58

**Comment by aexvir** [comment]
👋 Hi there,
Thanks for the feedback 🙂 

I've added a flag to skip pushing the image if the digest hasn't changed, it has been released in the [`v0.4.0`](https://github.com/aevea/action-kaniko/releases/tag/v0.4.0) tag

**Comment by somdoron** [comment]
Amazing, thanks!
