### ISSUE TITLE
Build args

### ISSUE THREAD

**Issue by hadim** [aevea/action-kaniko#6]
I would like to switch to this action (currently using https://github.com/docker/build-push-action) for the skip push feature but I am missing two features:

- Build args: https://github.com/docker/build-push-action#build_args
- Auto tagging with version number or branch name or `latest`: https://github.com/docker/build-push-action#tag_with_ref

**Comment by somdoron** [comment]
for build args you can use:
extra_args: --build-arg=ARG=value

**Comment by hadim** [comment]
Yes, this what I am using already. Thanks!

**Comment by aexvir** [comment]
I'll close this one as duplicate of https://github.com/aevea/action-kaniko/issues/9
