### ISSUE TITLE
Kaniko executor broken, outdated root certificates

### ISSUE THREAD

**Issue by pettermk** [aevea/action-kaniko#62]
This action has stopped working because in the Dockerfile, an outdated executor is being used (at least this is my working hypothesis)

I tested `v1.16.0` and found this to be working, but I don't know enough about the project to say whether this is a safe upgrade.

Repro:
```
docker run --rm -it --entrypoint sh gcr.io/kaniko-project/executor:v1.9.1-debug
/workspace # wget -O /kaniko/jq     https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```

**Comment by pettermk** [comment]
I found a fork with a fix and I can confirm that this is working for me. Bumped to `v1.18.0`
https://github.com/janatjak/action-kaniko

**Comment by fallion** [comment]
@aexvir  can you take a look please?

**Comment by aexvir** [comment]
v0.11.0 has all dependencies upgraded
apologies for the late reply and thanks for the report
